disabled_rules:
  - line_length
  - file_length
  - function_body_length
  - type_body_length
  - identifier_name  
  - type_name
  - trailing_whitespace
  - cyclomatic_complexity
  - function_parameter_count
  - trailing_comma
  - nesting

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation  
  - closure_spacing
  - contains_over_first_not_nil
  - empty_string
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - literal_expression_end_indentation
  - multiline_function_chains
  - multiline_parameters
  - object_literal 
  - operator_usage_whitespace  
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - switch_case_on_newline
  - vertical_parameter_alignment_on_call

excluded:
  - NounsTests
  - NounsUITests
  - NounsWatchTests
  - NounsWatchUITests
  - .build # Where Swift Package Manager checks out dependency sources
  - Nouns/Utils/R.generated.swift
  - NounsWatch WatchKit Extension/Utils/R.generated.swift
  - NounsServices/GraphQL/API.swift
